# Generated by Django 5.2.8 on 2025-11-30 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Электричество"),
                            ("cold_water", "Холодная вода"),
                            ("hot_water", "Горячая вода"),
                            ("gas", "Газ"),
                            ("heating", "Отопление"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "value_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid_at", models.DateField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Электричество"),
                            ("cold_water", "Холодная вода"),
                            ("hot_water", "Горячая вода"),
                            ("gas", "Газ"),
                            ("heating", "Отопление"),
                        ],
                        max_length=50,
                    ),
                ),
                ("unit", models.CharField(default="kwh", max_length=20)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("installed_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meters",
                        to="core.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=3, max_digits=12)),
                ("reading_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="core.meter",
                    ),
                ),
            ],
            options={
                "ordering": ["-reading_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Электричество"),
                            ("cold_water", "Холодная вода"),
                            ("hot_water", "Горячая вода"),
                            ("gas", "Газ"),
                            ("heating", "Отопление"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "consumption",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_charges",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("property", "year", "month", "resource_type")},
            },
        ),
    ]
